name: SimpleFly
version: 1.3.0
main: com.francobm.simplefly.SimpleFly
author: FrancoBM
description: Simplefly for this server.
commands:
  simplefly:
    description: simple fly command
    usage: /<command>
    aliases: [fly, volar, flight]